apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: example
spec:
  repositoryDigestMirrors:
  - mirrors:
    - vbastion.ocp4.clouddemos.pe:5000/ocp/openshift4
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - vbastion.ocp4.clouddemos.pe:5000/ocp/openshift4
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev

